apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP   
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}

