apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2025-04-14T10:47:35Z"
  generation: 28
  name: backend-release
  namespace: argocd
  resourceVersion: "208837"
  uid: f982f570-660d-40cf-8899-cc37a9e49268
spec:
  destination:
    namespace: 'helmdeployment '
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-backend.yaml
    path: helmTestingP/testingprojectHelm
    repoURL: https://github.com/NourBkh/k8s-config-repo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
status:
  conditions:
  - lastTransitionTime: "2025-04-14T11:00:52Z"
    message: 'Failed sync attempt to a6272cec9eebe011fc52c2eaacb701ab21187d88: one
      or more objects failed to apply, reason: namespaces "helmdeployment " not found
      (retried 5 times).'
    type: SyncError
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-04-14T10:55:21Z"
    status: Missing
  operationState:
    finishedAt: "2025-04-14T11:00:52Z"
    message: 'one or more objects failed to apply, reason: namespaces "helmdeployment
      " not found (retried 5 times).'
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: a6272cec9eebe011fc52c2eaacb701ab21187d88
    phase: Failed
    retryCount: 5
    startedAt: "2025-04-14T10:55:21Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/helmdeployment unchanged
        name: helmdeployment
        namespace: 'helmdeployment '
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Failed
        kind: ServiceAccount
        message: namespaces "helmdeployment " not found
        name: backend-release
        namespace: 'helmdeployment '
        status: SyncFailed
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Failed
        kind: Service
        message: namespaces "helmdeployment " not found
        name: backend-release
        namespace: 'helmdeployment '
        status: SyncFailed
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Failed
        kind: Deployment
        message: namespaces "helmdeployment " not found
        name: backend
        namespace: 'helmdeployment '
        status: SyncFailed
        syncPhase: Sync
        version: v1
      revision: a6272cec9eebe011fc52c2eaacb701ab21187d88
      source:
        helm:
          valueFiles:
          - values-backend.yaml
        path: helmTestingP/testingprojectHelm
        repoURL: https://github.com/NourBkh/k8s-config-repo.git
        targetRevision: HEAD
  reconciledAt: "2025-04-14T11:05:22Z"
  resources:
  - kind: Namespace
    name: helmdeployment
    status: Synced
    version: v1
  - health:
      status: Missing
    kind: Service
    name: backend-release
    namespace: 'helmdeployment '
    status: OutOfSync
    version: v1
  - health:
      status: Missing
    kind: ServiceAccount
    name: backend-release
    namespace: 'helmdeployment '
    status: OutOfSync
    version: v1
  - group: apps
    health:
      status: Missing
    kind: Deployment
    name: backend
    namespace: 'helmdeployment '
    status: OutOfSync
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: 'helmdeployment '
        server: https://kubernetes.default.svc
      source:
        helm:
          valueFiles:
          - values-backend.yaml
        path: helmTestingP/testingprojectHelm
        repoURL: https://github.com/NourBkh/k8s-config-repo.git
        targetRevision: HEAD
    revision: a6272cec9eebe011fc52c2eaacb701ab21187d88
    status: OutOfSync
