apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: pfe
  source:
    repoURL: 'https://your-git-repo-url/K8s-config-repo.git'
    targetRevision: HEAD
    path: azHelmDeployment
    helm:
      valueFiles:
        - values-frontend.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: azfrontend-app
  syncPolicy:
    automated: {}

