apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd  
spec:
  project: pfe  
  source:
    repoURL: https://github.com/NourBkh/k8s-config-repo.git  
    targetRevision: main  
    path: azArgocCD  
    helm:
      valueFiles:
        - values.yaml  
  destination:
    server: https://kubernetes.default.svc  
    namespace: ingress-nginx  
  syncPolicy:
    automated:
      prune: true  
      selfHeal: true  

