apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pfe
  namespace: argocd
spec:
  description: Project for PFE frontend and backend apps
  sourceRepos:
    - 'https://github.com/NourBkh/k8s-config-repo.git'
  destinations:
    - namespace: azpfe-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

