apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pfe
  namespace: argocd    # <--- YES! The AppProject itself is created inside the argocd namespace
spec:
  description: Project for PFE frontend and backend apps
  sourceRepos:
    - 'https://your-git-repo-url/K8s-config-repo.git'
  destinations:
    - namespace: azfrontend-app
      server: https://kubernetes.default.svc
    - namespace: azbackend-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

