backend:
  repository: nourbkh/testingprojectbackend
  pullPolicy: Always
  tag: "c32184a8"
  containerPort: 5000
  servicePort: 5000
  replicaCount: 1
  env:
    MONGO_URI: "mongodb+srv://nourbenkhairia:q679GFKo2oOUZFjd@cluster0.ugpumyv.mongodb.net/mydb?retryWrites=true&w=majority&appName=Cluster0"

frontend:
  repository: nourbkh/testingprojectfrontend
  pullPolicy: Always
  tag: "c32184a8"
  containerPort: 3000
  servicePort: 80
  replicaCount: 1
  env:
    REACT_APP_API_URL: "/api"
    
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: ""
      paths:
        - path: /api
          pathType: Prefix
        - path: /
          pathType: Prefix




