backend:
  repository: nourbkh/testingprojectbackend
  pullPolicy: Always
  tag: "45e253ed"
  containerPort: 5000
  servicePort: 5000
  replicaCount: 1
  env:
    MONGO_URI: ""

frontend:
  repository: nourbkh/testingprojectfrontend
  pullPolicy: Always
  tag: "45e253ed"
  containerPort: 3000
  servicePort: 80
  replicaCount: 1
  env:
    REACT_APP_API_URL: "/api/users/"
    
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host:
      paths:
        - path: /api/users/
          pathType: Prefix
        - path: /
          pathType: Prefix




