backend:
  repository: nourbkh/testingproject-backend
  pullPolicy: Always
  tag: "382cce22"
  containerPort: 5000
  servicePort: 5000
  replicaCount: 1
  env:
    MONGO_URI: "mongodb+srv://nourbenkhairia:q679GFKo2oOUZFjd@cluster0.ugpumyv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
"

frontend:
  repository: nourbkh/testingproject-frontend
  pullPolicy: Always
  tag: "382cce22"
  containerPort: 3000
  servicePort: 80
  replicaCount: 1
  env:
    REACT_APP_API_URL: "http://backend-service:5000"

