apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-stack-kube-prom-alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus-stack
    alertmanager: prometheus-stack-kube-prom-alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'slack-notifications'

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - send_resolved: true
            channel: '#alerts'
            username: 'PrometheusBot'
            api_url: 'https://hooks.slack.com/services/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'

