apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-rules
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
  - name: custom.rules
    rules:
    - alert: HighPodCPUUsage
      expr: rate(container_cpu_usage_seconds_total{container!="", pod!=""}[2m]) > 0.01
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage on pod
        description: Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using high CPU.

